server:
  port: 9000  #端口号

spring:
  application:
    name: discovery-eureka    #名称

eureka:
  instance:
    hostname: localhost   #host地址（名称）
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:   #服务路径
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/